export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_JOURNAL_SUCCESS = "FETCH_JOURNAL_SUCCESS";
export const ADD_JOURNAL_SUCCESS = "ADD_JOURNAL_SUCCESS";
